### PR TITLE
fix: (follow-up) use original interpreter path as 'home' value in pyv…

### PR DESCRIPTION
**Pull request by honnix**
…env.cfg

This is a follow-up of #226 to fix another place.

---

### Type of change

- Bug fix (change which fixes an issue)

**For changes visible to end-users**

- Suggested release notes are provided below:

Ensure correct home pathing is used when generating the venv.

### Test plan

- Manual testing; please provide instructions so we can reproduce:

As described by https://github.com/aspect-build/rules_py/pull/226#issuecomment-1833958996

### CODE REVIEW

**Comment by mattem** [comment]
Thanks @honnix, are you able to sign the CLA?

**Comment by honnix** [comment]
> Thanks @honnix, are you able to sign the CLA?

I will have to go through my employer so not sure how long it would take. Please feel free to pick up the change and discard this PR, as it is so small anyway :)

**Comment by honnix** [comment]
@mattem This is a somewhat annoying bug. To unblock the fix I will close this PR and please help fix it. Thank you!

**Comment by honnix** [comment]
Looks like this has not been solved. Could you please help fix it @mattem ? Thank you.

**Pull request closed without merging**
