### PR TITLE
fix: venv should require exec toolchain

### PR DESCRIPTION
**Pull request by thesayyn**
### Type of change

- Bug fix (change which fixes an issue)

### Test plan

- New test cases added

- TODO: add test

### CODE REVIEW

**Comment by thesayyn** [comment]
I'll talk about this with @alexeagle tmr

**Review by alexeagle — COMMENTED** [review]
I think there's some useful feedback on the slack thread, let's see if someone like @fmeum can provide a more thorough and correct review than I can

**Comment by fmeum** [comment]
This is very interesting. I will need to think this through a bit more before I can provide meaningful comments.

**Review by fmeum — COMMENTED** [review]
This appears to be a pretty complicated workaround for an underlying issue with toolchain registration and I am not sure it will work properly in cross-platform setups.

I noticed that your primary toolchain definition at https://github.com/aspect-build/rules_py/blob/218a202c6467ffe109b56d7af0a49932a2ccc46c/py/private/toolchain/autodetecting.bzl#L43 lacks a `target_compatible_with` attribute. With that added, you could presumably just define a `py_binary` target that serves as the `venv` tool and add that as an `exec` dep of the `venv` rule.

It's possible that I'm missing something and this requires a more complex solution, but a `toolchain` without constraints is almost never correct.

**Comment by thesayyn** [comment]
eh this bit me again, didn't know this was already here...

**Comment by thesayyn** [comment]
> It's possible that I'm missing something and this requires a more complex solution, but a `toolchain` without constraints is almost never correct.

good point. 

> you could presumably just define a `py_binary` target that serves as the `venv` tool and add that as an `exec` dep of the `venv` rule.

wouldn't this almost be same as what I do right now with getting the python toolchain for the exec but a level more indirection? 

Also, i presume auto exec groups ought to fix this, maybe correct solution is to wait for that?

**Comment by fmeum** [comment]
It's similar, but avoids having to introduce a `current_runtime` rule, which ends up hiding the actual source of a toolchain requirement and thus makes it harder to debug toolchain resolution issues.

I don't know auto exec groups well enough to assess whether they could help here.

**Comment by alexeagle** [comment]
We'll solve for this by introducing a new toolchain pair, since we actually need to run a different command in the `exec` cfg than we do in the `target` cfg. See pycrust branch.

**Pull request closed without merging**
