### PR TITLE
fix: handle a system interpreter path on the toolchain

### LINKED ISSUE #302: [Bug]: "unbound variable" error in py_test, py_binary when using py_runtime with interpreter_path set
### What happened?

I declared a custom toolchain that points at the system python interpreter.

```starlark
load("@rules_python//python:defs.bzl", "py_runtime", "py_runtime_pair")

py_runtime(
    name = "my_py3_runtime",
    interpreter_path = "/usr/bin/python",
    interpreter_version_info = {
        "major": "3",
        "minor": "10",
        "micro": "8",
    },
    python_version = "PY3",
)

py_runtime_pair(
    name = "my_py_runtime_pair",
    py2_runtime = None,
    py3_runtime = ":my_py3_runtime",
)

toolchain(
    name = "default",
    toolchain = ":my_py_runtime_pair",
    toolchain_type = "@bazel_tools//tools/python:toolchain_type",
)
```

I registered it in MODULE.bazel:
```starlark
register_toolchains("//toolchain:default")
```

When I tried to run a `py_test`, the sh wrapper failed:
```console
$ bazel test --action_env=RUNFILES_LIB_DEBUG=1 src_test
==================== Test output for //:src_test:
INFO[runfiles.bash]: rlocation(aspect_rules_py~override/py/tools/venv_bin/venv_bin): start
INFO[runfiles.bash]: runfiles_current_repository(2): caller's path is (/tmp/bazel-working-directory/_main/bazel-out/k8-fastbuild/bin/src_test.runfiles/_main/src_test)
INFO[runfiles.bash]: runfiles_current_repository(2): (/tmp/bazel-working-directory/_main/bazel-out/k8-fastbuild/bin/src_test.runfiles/_main/src_test) has path (_main/src_test) relative to the runfiles directory (/tmp/bazel-working-directory/_main/bazel-out/k8-fastbuild/bin/src_test.runfiles)
INFO[runfiles.bash]: runfiles_current_repository(2): (/tmp/bazel-working-directory/_main/bazel-out/k8-fastbuild/bin/src_test.runfiles/_main/src_test) corresponds to rlocation path (_main/src_test)
INFO[runfiles.bash]: runfiles_current_repository(2): (_main/src_test) lies in the main repository
INFO[runfiles.bash]: rlocation(aspect_rules_py~override/py/tools/venv_bin/venv_bin): looking up canonical name for (aspect_rules_py~override) from () in (/tmp/bazel-working-directory/_main/bazel-out/k8-fastbuild/bin/src_test.runfiles/_repo_mapping)
INFO[runfiles.bash]: rlocation(aspect_rules_py~override/py/tools/venv_bin/venv_bin): canonical name of target repo is ()
INFO[runfiles.bash]: rlocation(aspect_rules_py~override/py/tools/venv_bin/venv_bin): found under RUNFILES_DIR (/tmp/bazel-working-directory/_main/bazel-out/k8-fastbuild/bin/src_test.runfiles), return
INFO[runfiles.bash]: rlocation(_main//usr/bin/python): start
ERROR[runfiles.bash]: rlocation(_main//usr/bin/python): path is not normalized
/tmp/bazel-working-directory/_main/bazel-out/k8-fastbuild/bin/src_test.runfiles/_main/src_test: line 25: $1: unbound variable
INFO[runfiles.bash]: rlocation(_main/src_test.venv.pth): start
INFO[runfiles.bash]: runfiles_current_repository(2): caller's path is (/tmp/bazel-working-directory/_main/bazel-out/k8-fastbuild/bin/src_test.runfiles/_main/src_test)
INFO[runfiles.bash]: runfiles_current_repository(2): (/tmp/bazel-working-directory/_main/bazel-out/k8-fastbuild/bin/src_test.runfiles/_main/src_test) has path (_main/src_test) relative to the runfiles directory (/tmp/bazel-working-directory/_main/bazel-out/k8-fastbuild/bin/src_test.runfiles)
INFO[runfiles.bash]: runfiles_current_repository(2): (/tmp/bazel-working-directory/_main/bazel-out/k8-fastbuild/bin/src_test.runfiles/_main/src_test) corresponds to rlocation path (_main/src_test)
INFO[runfiles.bash]: runfiles_current_repository(2): (_main/src_test) lies in the main repository
INFO[runfiles.bash]: rlocation(_main/src_test.venv.pth): looking up canonical name for (_main) from () in (/tmp/bazel-working-directory/_main/bazel-out/k8-fastbuild/bin/src_test.runfiles/_repo_mapping)
INFO[runfiles.bash]: rlocation(_main/src_test.venv.pth): canonical name of target repo is ()
INFO[runfiles.bash]: rlocation(_main/src_test.venv.pth): found under RUNFILES_DIR (/tmp/bazel-working-directory/_main/bazel-out/k8-fastbuild/bin/src_test.runfiles), return
error: a value is required for '--python <PYTHON>' but none was supplied
```

### Version

Development (host) and target OS/architectures: linux x86-64

Output of `bazel --version`: bazel 7.0.2

Version of the Aspect rules: rules_py 6962d6af35949bf62b9f62025ffddbee12beb7af (also v0.7.1)

Language(s) and/or frameworks involved: Python 3.10.8 (happens with 3.9, 3.11 as well)

### How to reproduce

After defining the python toolchain as shown above, trying to run any `py_test` or `py_binary` target will reproduce the problem.

Min repro:
https://github.com/wade-arista/bazel-demo/tree/23ff2cebe6058a5e99535bd3f76c72b1b2b188ce 

Test run:
https://github.com/wade-arista/bazel-demo/actions/runs/8209925408/job/22456408401#step:4:615

### Any other information?

```
ERROR[runfiles.bash]: rlocation(_main//usr/bin/python): path is not normalized
/tmp/bazel-working-directory/_main/bazel-out/k8-fastbuild/bin/src_test.runfiles/_main/src_test: line 25: $1: unbound variable
```
It's trying to resolve `{{ARG_PYTHON}}` in 

```
"${VENV_TOOL}" \
    --location "${VIRTUAL_ENV}" \
    --python "$(alocation $(rlocation {{ARG_PYTHON}}))" \
    --python-version "{{ARG_VENV_PYTHON_VERSION}}" \
    --pth-file "$(rlocation {{ARG_PTH_FILE}})"
```

See https://github.com/aspect-build/rules_py/blob/734070be63e91e9f7e1abffc7cb8a03d615e3ccf/py/private/run.tmpl.sh#L27-L31 and https://github.com/aspect-build/rules_py/blob/734070be63e91e9f7e1abffc7cb8a03d615e3ccf/py/private/py_binary.bzl#L72

### PR DESCRIPTION
**Pull request by mattem**
Handles the path being given to the Python toolchain being a system interpreter.

Closes #302

---

### Type of change

- Bug fix (change which fixes an issue)

**For changes visible to end-users**

- Suggested release notes are provided below:
Correctly handle a system interpreter path being set on a Python toolchain.

### Test plan

- Covered by existing test cases
- Manual testing; please provide instructions so we can reproduce:

Manual testing with local interpreter.

### CODE REVIEW

**Review by alexeagle — COMMENTED** [review]
could we add some e2e test that relies on a system interpreter intentionally?

I think we're behind on automated testing and will make this ruleset too much burden to maintain

**Comment by mattem** [comment]
I can try, will have to ensure CI has a system interpreter in the expect place.

**Review by alexeagle — APPROVED** [review]
Do you think we actually require coverage of this feature under both bzlmod and WORKSPACE? unless there are repository rules and/or module extensions involved, we'll save time and money by only setting up one of them for this new e2e

**Comment by mattem** [comment]
> Do you think we actually require coverage of this feature under both bzlmod and WORKSPACE? unless there are repository rules and/or module extensions involved, we'll save time and money by only setting up one of them for this new e2e

Probably not, but I don't know how to operate the CI system here so it only does one.

**Pull request merged**
